# -----------------------------------------------------------------------------
# Look up the latest official Ubuntu 22.04 AMI instead of hardcoding an AMI ID.
# AMI IDs are region-specific and change over time - hardcoding one is a common
# beginner mistake that breaks the moment you change region or AWS updates it.
# -----------------------------------------------------------------------------
data "aws_ami" "ubuntu" {
  most_recent = true
  owners      = ["099720109477"] # Canonical's official AWS account ID

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*"]
  }
}

# -----------------------------------------------------------------------------
# SSH key pair - generated by Terraform itself so you don't need to click
# "create key pair" in the AWS console. The private key gets saved locally.
# -----------------------------------------------------------------------------
resource "tls_private_key" "jenkins_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "aws_key_pair" "jenkins_key" {
  key_name   = "${var.project_name}-jenkins-key"
  public_key = tls_private_key.jenkins_key.public_key_openssh
}

resource "local_file" "private_key" {
  content         = tls_private_key.jenkins_key.private_key_pem
  filename        = "${path.module}/${var.project_name}-jenkins-key.pem"
  file_permission = "0400" # SSH refuses to use a key with looser permissions
}

# -----------------------------------------------------------------------------
# Security group - the instance-level firewall. Only these exact ports/sources
# are allowed in; everything else is blocked by default.
# -----------------------------------------------------------------------------
resource "aws_security_group" "jenkins_sg" {
  name        = "${var.project_name}-jenkins-sg"
  description = "Allow SSH, Jenkins UI, SonarQube UI"
  vpc_id      = var.vpc_id

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = [var.allowed_ssh_cidr]
  }

  ingress {
    description = "Jenkins UI"
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description = "SonarQube UI"
    from_port   = 9000
    to_port     = 9000
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    description = "Allow all outbound (needed to pull packages, push to DockerHub, reach EKS API)"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "${var.project_name}-jenkins-sg"
  }
}

# -----------------------------------------------------------------------------
# The actual EC2 instance. user_data = the install script - EC2 runs it
# automatically as root the FIRST time the instance boots, nothing manual.
# -----------------------------------------------------------------------------
resource "aws_instance" "jenkins" {
  ami                    = data.aws_ami.ubuntu.id
  instance_type          = var.instance_type
  subnet_id              = var.subnet_id
  key_name               = aws_key_pair.jenkins_key.key_name
  vpc_security_group_ids = [aws_security_group.jenkins_sg.id]

  root_block_device {
    volume_size = 30 # Jenkins + SonarQube + Docker images need more than the 8GB default
    volume_type = "gp3"
  }

  user_data = file("${path.module}/../../scripts/install-tools.sh")

  tags = {
    Name = "${var.project_name}-jenkins-server"
  }
}
